[functions.match-livekit-token]
verify_jwt = false

[functions.livekit-token]
verify_jwt = false

[functions.end-event-room]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.livekit-webhook]
verify_jwt = false

[functions.admin-delete-room]
verify_jwt = false

[functions.dispatch-push-notifications]
verify_jwt = false

[functions.float-match]
verify_jwt = false
