[functions.match-livekit-token]
verify_jwt = false

[functions.livekit-token]
verify_jwt = false

[functions.end-event-room]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.livekit-webhook]
verify_jwt = false
