create extension if not exists pgcrypto;

create table if not exists public.site_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin')),
  granted_by uuid null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null,
  action text not null,
  target_type text not null,
  target_id text null,
  reason text not null check (char_length(reason) between 5 and 500),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists site_admin_audit_log_created_idx
  on public.site_admin_audit_log(created_at desc);

alter table public.site_admins enable row level security;
alter table public.site_admin_audit_log enable row level security;

revoke all on public.site_admins from public, anon, authenticated;
revoke all on public.site_admin_audit_log from public, anon, authenticated;

create or replace function public.is_site_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select auth.uid() is not null
    and exists (
      select 1
      from public.site_admins administrator
      where administrator.user_id = auth.uid()
    );
$$;

revoke all on function public.is_site_admin() from public, anon, authenticated;
grant execute on function public.is_site_admin() to authenticated;

do $$
declare
  v_admin_user_id uuid;
begin
  select account.id
  into v_admin_user_id
  from auth.users account
  where lower(account.email) = 'dwalker2525@gmail.com'
  order by account.created_at
  limit 1;

  if v_admin_user_id is null then
    raise exception 'Cannot grant PartyUp admin access: dwalker2525@gmail.com was not found in auth.users';
  end if;

  insert into public.site_admins (user_id, role, granted_by)
  values (v_admin_user_id, 'admin', v_admin_user_id)
  on conflict (user_id) do update set role = excluded.role;

  insert into public.site_admin_audit_log (
    admin_user_id, action, target_type, target_id, reason, metadata
  ) values (
    v_admin_user_id,
    'grant_site_admin',
    'auth_user',
    v_admin_user_id::text,
    'Initial PartyUp administrator bootstrap',
    jsonb_build_object('email', 'dwalker2525@gmail.com', 'role', 'admin')
  );
end;
$$;

create or replace function public.get_site_admin_dashboard(p_search text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_search text := left(lower(btrim(coalesce(p_search, ''))), 100);
begin
  if not public.is_site_admin() then
    raise exception 'Site administrator access required';
  end if;

  return jsonb_build_object(
    'counts', jsonb_build_object(
      'users', (select count(*) from auth.users),
      'open_reports', (select count(*) from public.room_message_reports report where report.status = 'open'),
      'active_rooms', (select count(*) from public.event_rooms room where room.status::text <> 'ended'),
      'live_rooms', (select count(*) from public.room_live_state state where state.is_live),
      'failed_deletions', (select count(*) from public.account_deletion_requests request where request.status = 'failed')
    ),
    'reports', coalesce((
      select jsonb_agg(to_jsonb(report_row) order by report_row.created_at desc)
      from (
        select
          report.id,
          report.room_id,
          report.message_id,
          report.reported_user_id,
          report.reason,
          report.details,
          report.message_snapshot,
          report.display_name_snapshot,
          report.status,
          report.resolution,
          report.created_at,
          report.reviewed_at,
          coalesce(to_jsonb(room)->>'title', to_jsonb(room)->>'name', 'Event room') as room_title
        from public.room_message_reports report
        left join public.event_rooms room on room.id = report.room_id
        order by case when report.status = 'open' then 0 else 1 end, report.created_at desc
        limit 50
      ) report_row
    ), '[]'::jsonb),
    'users', coalesce((
      select jsonb_agg(to_jsonb(user_row) order by user_row.created_at desc)
      from (
        select
          account.id,
          account.email,
          account.created_at,
          account.last_sign_in_at,
          profile.username,
          profile.avatar_url,
          administrator.role as admin_role
        from auth.users account
        left join public.profiles profile on profile.id = account.id
        left join public.site_admins administrator on administrator.user_id = account.id
        where v_search = ''
          or lower(coalesce(account.email, '')) like '%' || v_search || '%'
          or lower(coalesce(profile.username, '')) like '%' || v_search || '%'
          or account.id::text = v_search
        order by account.created_at desc
        limit 50
      ) user_row
    ), '[]'::jsonb),
    'rooms', coalesce((
      select jsonb_agg(to_jsonb(room_row) order by room_row.last_active_at desc nulls last)
      from (
        select
          room.id,
          room.host_id,
          room.status::text as status,
          coalesce(to_jsonb(room)->>'title', to_jsonb(room)->>'name', 'Event room') as title,
          coalesce(room.is_private, false) as is_private,
          coalesce(room.current_users, 0) as current_users,
          coalesce(room.queue_count, 0) as queue_count,
          room.last_active_at,
          profile.username as host_username,
          coalesce(live_state.is_live, false) as is_live,
          coalesce(live_state.active_publisher_count, 0) as active_publisher_count,
          live_state.signal_source,
          live_state.updated_at as live_state_updated_at
        from public.event_rooms room
        left join public.profiles profile on profile.id = room.host_id
        left join public.room_live_state live_state on live_state.room_id = room.id
        order by
          case when room.status::text <> 'ended' then 0 else 1 end,
          room.last_active_at desc nulls last
        limit 75
      ) room_row
    ), '[]'::jsonb),
    'deletion_requests', coalesce((
      select jsonb_agg(to_jsonb(deletion_row) order by deletion_row.requested_at desc)
      from (
        select
          request.request_id,
          left(request.account_fingerprint, 12) as account_fingerprint,
          request.status,
          request.requested_at,
          request.completed_at,
          request.last_error
        from public.account_deletion_requests request
        order by request.requested_at desc
        limit 30
      ) deletion_row
    ), '[]'::jsonb),
    'audit_log', coalesce((
      select jsonb_agg(to_jsonb(audit_row) order by audit_row.created_at desc)
      from (
        select
          audit.id,
          audit.admin_user_id,
          account.email as admin_email,
          audit.action,
          audit.target_type,
          audit.target_id,
          audit.reason,
          audit.metadata,
          audit.created_at
        from public.site_admin_audit_log audit
        left join auth.users account on account.id = audit.admin_user_id
        order by audit.created_at desc
        limit 50
      ) audit_row
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_review_room_message_report(
  p_report_id uuid,
  p_action text,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_admin_user_id uuid := auth.uid();
  v_action text := lower(btrim(coalesce(p_action, '')));
  v_reason text := btrim(coalesce(p_reason, ''));
  v_report public.room_message_reports;
  v_room public.event_rooms;
  v_resolution text;
  v_muted_until timestamptz;
  v_message_removed boolean := false;
begin
  if not public.is_site_admin() then
    raise exception 'Site administrator access required';
  end if;

  if char_length(v_reason) not between 5 and 500 then
    raise exception 'An audit reason between 5 and 500 characters is required';
  end if;

  if v_action not in ('dismiss', 'remove_message', 'mute_5m') then
    raise exception 'Unsupported report action';
  end if;

  select report.* into v_report
  from public.room_message_reports report
  where report.id = p_report_id
  for update;

  if not found then
    raise exception 'Report not found';
  end if;

  if v_report.status <> 'open' then
    raise exception 'This report has already been reviewed';
  end if;

  select room.* into v_room
  from public.event_rooms room
  where room.id = v_report.room_id;

  if v_action = 'dismiss' then
    v_resolution := 'dismissed';
  elsif v_action = 'remove_message' then
    update public.room_messages message
    set message = '[removed]',
        removed_at = now(),
        removed_by = v_admin_user_id,
        removal_reason = 'site_admin_removed'
    where message.id = v_report.message_id
      and message.removed_at is null;

    v_message_removed := found;
    v_resolution := case when v_message_removed then 'message_removed' else 'message_already_removed' end;
  else
    if v_room.id is null then
      raise exception 'The originating room is no longer available';
    end if;

    if v_report.reported_user_id is null
       or not exists (select 1 from auth.users account where account.id = v_report.reported_user_id) then
      raise exception 'The reported account is no longer available';
    end if;

    if v_report.reported_user_id = v_room.host_id then
      raise exception 'The room host cannot be muted';
    end if;

    v_muted_until := now() + interval '5 minutes';

    insert into public.room_chat_mutes (
      room_id, target_user_id, muted_until, created_by, reason, created_at
    ) values (
      v_report.room_id,
      v_report.reported_user_id,
      v_muted_until,
      v_admin_user_id,
      'Muted by a PartyUp site administrator: ' || v_reason,
      now()
    )
    on conflict (room_id, target_user_id) do update
    set muted_until = excluded.muted_until,
        created_by = excluded.created_by,
        reason = excluded.reason,
        created_at = now();

    v_resolution := 'user_muted_5m';
  end if;

  update public.room_message_reports
  set status = case when v_action = 'dismiss' then 'dismissed' else 'resolved' end,
      resolution = v_resolution,
      reviewed_by_user_id = v_admin_user_id,
      reviewed_at = now()
  where id = v_report.id;

  if v_room.id is not null then
    insert into public.room_moderation_actions (
      room_id, message_id, target_user_id, moderator_user_id, action, metadata
    ) values (
      v_report.room_id,
      v_report.message_id,
      v_report.reported_user_id,
      v_admin_user_id,
      case
        when v_action = 'dismiss' then 'report_dismissed'
        when v_action = 'mute_5m' then 'user_muted_5m'
        else 'report_resolved'
      end,
      jsonb_build_object(
        'report_id', v_report.id,
        'resolution', v_resolution,
        'site_admin', true,
        'reason', v_reason,
        'muted_until', v_muted_until
      )
    );
  end if;

  insert into public.site_admin_audit_log (
    admin_user_id, action, target_type, target_id, reason, metadata
  ) values (
    v_admin_user_id,
    'review_message_report:' || v_action,
    'room_message_report',
    v_report.id::text,
    v_reason,
    jsonb_build_object(
      'room_id', v_report.room_id,
      'message_id', v_report.message_id,
      'reported_user_id', v_report.reported_user_id,
      'resolution', v_resolution
    )
  );

  return jsonb_build_object(
    'id', v_report.id,
    'status', case when v_action = 'dismiss' then 'dismissed' else 'resolved' end,
    'resolution', v_resolution,
    'muted_until', v_muted_until
  );
end;
$$;

create or replace function public.admin_manage_event_room(
  p_room_id uuid,
  p_action text,
  p_reason text,
  p_participant_message text default null
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_admin_user_id uuid := auth.uid();
  v_action text := lower(btrim(coalesce(p_action, '')));
  v_reason text := btrim(coalesce(p_reason, ''));
  v_participant_message text := nullif(btrim(coalesce(p_participant_message, '')), '');
  v_room public.event_rooms;
  v_clear_event_id uuid;
  v_removed_count integer := 0;
  v_action_at timestamptz := now();
begin
  if not public.is_site_admin() then
    raise exception 'Site administrator access required';
  end if;

  if char_length(v_reason) not between 5 and 500 then
    raise exception 'An audit reason between 5 and 500 characters is required';
  end if;

  if v_action not in ('clear', 'end') then
    raise exception 'Unsupported room action';
  end if;

  if v_participant_message is not null and char_length(v_participant_message) > 500 then
    raise exception 'The participant message must be 500 characters or fewer';
  end if;

  select room.* into v_room
  from public.event_rooms room
  where room.id = p_room_id
  for update;

  if not found then
    raise exception 'Room not found';
  end if;

  if v_room.status::text = 'ended' then
    raise exception 'This room has already ended';
  end if;

  if v_action = 'clear' then
    if v_room.host_id is null then
      raise exception 'A room without a host cannot be cleared';
    end if;

    insert into public.room_clear_events (room_id, host_id, message, created_at)
    values (p_room_id, v_room.host_id, v_participant_message, v_action_at)
    returning id into v_clear_event_id;

    insert into public.room_clear_recipients (
      clear_event_id, user_id, username, previous_status, created_at
    )
    select
      v_clear_event_id,
      attendee.user_id,
      attendee.username,
      attendee.status::text,
      v_action_at
    from public.event_attendees attendee
    where attendee.event_room_id = p_room_id
      and attendee.user_id <> v_room.host_id
    on conflict (clear_event_id, user_id) do nothing;

    get diagnostics v_removed_count = row_count;

    update public.room_clear_events
    set removed_count = v_removed_count
    where id = v_clear_event_id;

    delete from public.event_attendees attendee
    where attendee.event_room_id = p_room_id
      and attendee.user_id <> v_room.host_id;
  else
    update public.event_attendees
    set can_stream = false,
        stream_status = 'off',
        status = case
          when status::text in ('waiting', 'pending', 'requested', 'queued') then 'left'
          else status
        end
    where event_room_id = p_room_id;
  end if;

  delete from public.room_chat_mutes where room_id = p_room_id;

  delete from public.match_queue queue
  using public.match_pools pool
  where queue.pool_id = pool.id
    and pool.pool_type::text = 'event'
    and pool.source_id = p_room_id;

  update public.match_sessions session
  set status = 'ended',
      ended_at = coalesce(session.ended_at, v_action_at),
      ended_reason = coalesce(session.ended_reason, case when v_action = 'clear' then 'room_cleared' else 'event_ended' end)
  from public.match_pools pool
  where session.pool_id = pool.id
    and pool.pool_type::text = 'event'
    and pool.source_id = p_room_id
    and session.status::text <> 'ended';

  if v_action = 'end' then
    update public.match_pools
    set status = 'ended', expires_at = v_action_at
    where pool_type::text = 'event' and source_id = p_room_id;

    update public.room_announcements
    set is_active = false, updated_at = v_action_at
    where room_id = p_room_id and is_active = true;
  end if;

  if to_regclass('public.room_presence') is not null then
    execute 'delete from public.room_presence where room_id = $1' using p_room_id;
  end if;

  if to_regclass('public.room_typing') is not null then
    execute 'delete from public.room_typing where room_id = $1' using p_room_id;
  end if;

  if to_regclass('public.room_live_publishers') is not null then
    delete from public.room_live_publishers where room_id = p_room_id;
  end if;

  if to_regclass('public.room_live_state') is not null then
    insert into public.room_live_state (
      room_id, is_live, active_publisher_count, signal_authoritative, signal_source, updated_at
    ) values (
      p_room_id, false, 0, true, 'site_admin:' || v_action, v_action_at
    )
    on conflict (room_id) do update
    set is_live = false,
        active_publisher_count = 0,
        signal_authoritative = true,
        signal_source = excluded.signal_source,
        updated_at = excluded.updated_at;
  end if;

  if v_action = 'end' then
    if to_regclass('public.room_stream_keys') is not null then
      execute 'delete from public.room_stream_keys where room_id = $1' using p_room_id;
    end if;

    perform set_config('partyup.ending_room_id', p_room_id::text, true);

    update public.event_rooms
    set status = 'ended', current_users = 0, queue_count = 0, last_active_at = v_action_at
    where id = p_room_id;
  else
    update public.event_rooms
    set current_users = 0, queue_count = 0, last_active_at = v_action_at
    where id = p_room_id;
  end if;

  insert into public.site_admin_audit_log (
    admin_user_id, action, target_type, target_id, reason, metadata
  ) values (
    v_admin_user_id,
    'manage_room:' || v_action,
    'event_room',
    p_room_id::text,
    v_reason,
    jsonb_build_object(
      'clear_event_id', v_clear_event_id,
      'removed_count', v_removed_count,
      'participant_message_sent', v_participant_message is not null
    )
  );

  return jsonb_build_object(
    'room_id', p_room_id,
    'action', v_action,
    'removed_count', v_removed_count,
    'clear_event_id', v_clear_event_id,
    'completed_at', v_action_at
  );
end;
$$;

revoke all on function public.get_site_admin_dashboard(text) from public, anon, authenticated;
revoke all on function public.admin_review_room_message_report(uuid, text, text) from public, anon, authenticated;
revoke all on function public.admin_manage_event_room(uuid, text, text, text) from public, anon, authenticated;

grant execute on function public.get_site_admin_dashboard(text) to authenticated;
grant execute on function public.admin_review_room_message_report(uuid, text, text) to authenticated;
grant execute on function public.admin_manage_event_room(uuid, text, text, text) to authenticated;

notify pgrst, 'reload schema';
